/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
/* Header for class com_hsdi_x264test_X264Test */

#ifndef _Included_com_hsdi_x264test_X264Test
#define _Included_com_hsdi_x264test_X264Test
#ifdef __cplusplus
extern "C" {
#endif

#include<x264.h>

	/*
	 * Class:     com_hsdi_x264test_X264Test
	 * Method:    CppTest
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_hsdi_x264test_X264Test_CppTest
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
