/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
/* Header for class com_hsdi_x264test_X264Test */

#ifndef _Included_com_hsdi_x264test_X264Test
#define _Included_com_hsdi_x264test_X264Test
#ifdef __cplusplus
extern "C" {
#endif

#include<x264.h>

	/*
	 * Class:     com_hsdi_x264test_X264Test
	 * Method:    CppTest
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_hsdi_x264test_X264Test_CppTest
		(JNIEnv *, jclass);

	/*
	 * Class:     com_hsdi_x264test_X264Test
	 * Method:    x264_test_init
	 * Signature: (II)J
	 */
	JNIEXPORT jlong JNICALL Java_com_hsdi_x264test_X264Test_x264_1test_1init
		(JNIEnv *, jclass, jint, jint);

	/*
	 * Class:     com_hsdi_x264test_X264Test
	 * Method:    x264_test_encode
	 * Signature: (JI[BI[B)I
	 */
	JNIEXPORT jint JNICALL Java_com_hsdi_x264test_X264Test_x264_1test_1encode
		(JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jbyteArray);

	/*
	 * Class:     com_hsdi_x264test_X264Test
	 * Method:    x264_test_finish
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_com_hsdi_x264test_X264Test_x264_1test_1finish
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
