/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hsdi_x264test_FFmpegTest */

#ifndef _Included_com_hsdi_x264test_FFmpegTest
#define _Included_com_hsdi_x264test_FFmpegTest
#ifdef __cplusplus
extern "C" {
#endif

#define __STDC_CONSTANT_MACROS

#ifdef _STDINT_H
#undef _STDINT_H
#endif

#include<libavformat\avformat.h>
#include<libavutil\avutil.h>
#include<libavcodec\avcodec.h>
#include<stdint.h>

	/*
	 * Class:     com_hsdi_x264test_FFmpegTest
	 * Method:    ffpmeg_pack_h264_2_mp4
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_com_hsdi_x264test_FFmpegTest_ffpmeg_1pack_1h264_12_1mp4
		(JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
